### ISSUE TITLE
Empty bibliography

### ISSUE THREAD

**Issue by KarhouTam** [Nazzcjy/SZUThesisLatest#4]
同学你好，目前我在使用这份模板时，在 Biblio/ref.bib 中添加了我的 bibtex 引用，但编译时没有识别到。
![image](https://github.com/Nazzcjy/SZUThesisLatest/assets/82705454/b066f4b9-7a60-4375-910e-76eb03e3246b)
若加上 \bibliography{Biblio/ref.bib}
则有以下报错
![image](https://github.com/Nazzcjy/SZUThesisLatest/assets/82705454/d9bf4a77-39a0-4a08-8c6e-1a7de9f842b1)

请问应该如何正确引入 ref.bib 这个文件

**Comment by cflee123** [comment]
请尝试将ref.bib文件拖动到与main.tex文件同级目录，另外，`\bibliography{}`命令需要被放置在latex代码的前言部分，即`\begin{document}`命令之前的部分

**Comment by KarhouTam** [comment]
照做了，但还是存在问题。
![image](https://github.com/Nazzcjy/SZUThesisLatest/assets/82705454/bec51fef-722e-4d8f-8402-ad0f334b7415)
![image](https://github.com/Nazzcjy/SZUThesisLatest/assets/82705454/3434ef50-cb36-4334-ae49-e546fc38ce9b)

请问运行这个模板的 os 有要求吗？我是在 wsl2 的 ubuntu 2204上运行的。

**Comment by cflee123** [comment]
请问你将两者放在同一级目录下调整了config.tex文件相应的地方吗，你把`\bibliography{}`放在`\input{}`之前，那么编译后文献路径是config.tex中的设置。

**Comment by KarhouTam** [comment]
config.tex的位置我没有调整过，目前是跟 main.tex 和 ref.bib 在同一目录下。

> 你把\bibliography{}放在\input{}之前，那么编译后文献路径是config.tex中的设置

无论我把 \bibliography{} 放在 input{config} 前还是后都没能解决我的问题。

**Comment by cflee123** [comment]
![image](https://github.com/Nazzcjy/SZUThesisLatest/assets/131333379/b65b7d01-9c4d-4977-9f39-2860a7074a17)
抱歉我说的是config.tex文件中有关参考文献路径设置的语句，应该在第31行，你或许需要改一下这个地方，并建议先注释掉`\bibliography{}`

**Comment by cflee123** [comment]
另外，刚刚查看了` \bibliography{}`的使用文档，他的使用需要如下几步：
1. 首先，在LaTeX文档的前言部分，需要包含一个引用样式包，比如`\usepackage{natbib}`或者其他的引用管理包。
2. 在文档的内容部分，使用`\cite{标识符}`命令来引用.bib文件中的参考文献条目。
3. 在文档的末尾，使用`\bibliography{文件名}`命令来指定.bib文件的名称（不包括扩展名）。例如，如果你的参考文献文件名为references.bib，则命令为`\bibliography{references}`。
4. 还需要使用`\bibliographystyle{样式}`命令来指定参考文献的格式样式，比如`\bibliographystyle{plainnat}`。

**Comment by KarhouTam** [comment]
在将 ref.bib 移至跟 config.tex main.tex 同一目录下后我修改了
![image](https://github.com/Nazzcjy/SZUThesisLatest/assets/82705454/acfe25d8-3913-4c10-9ced-0daefe70fd71)
但依然无法识别

关于同学你对 bibliography 的介绍，之前我在投小论文时确实是这么做的，但我对这种自定义的latex模板比较苦手，所以还请多包涵。

**Comment by cflee123** [comment]
这个问题也有其他人遇到过，也有同学没有遇到，所以具体是什么问题还不是很清楚，我只能跟你说目前已经了解到的经验，一个是目录级别，第二个是编译器选择xelatex。另外，虽然我之前也遇到过这种问题，但当时主要关注包冲突问题，所以后来他突然好了我也没有注意是修改了哪里，所以我建议你先把所以自用包注释掉，清除所有编译过程中的中间文件，如果问题依然存在，你可以试着将`\addbibresource{}`注释，使用你曾经使用过的文献引用方式。此外，就系统环境而言，我了解到的只有windows和macos两种，这个项目在这两种环境下可以成功运行，仅在字体设置方面有所不同，如果后续你的问题得到解决，我们也欢迎你能在评论区留言，同样，如果你对项目有改进建议，也欢迎fork我们的项目提交你的改动。

**Comment by KarhouTam** [comment]
好的谢谢同学
